from dotenv import load_dotenv
load_dotenv()

from utils import pretty_print
from schemas import EssayState
from build_graph import workflow

topic = "It's best to see Life as a journey, not a destination."
essay = """Indian philosophy has long proclaimed, “Santosham param sukham” – contentment is the greatest happiness. The saying, “Contentment is natural wealth; luxury is artificial poverty,” beautifully captures this eternal wisdom. It implies that true prosperity lies not in possessing more, but in feeling fulfilled with what one has. Conversely, unending desires and the pursuit of luxury create a sense of inner emptiness – a kind of poverty masked by material abundance. In essence, while contentment springs from within and reflects harmony with oneself and nature, luxury often stems from external craving and comparison, leaving the individual spiritually impoverished despite material success. This profound thought, rooted deeply in Indian and global philosophical traditions, reminds us that real wealth lies in peace of mind and simplicity, not in the glitter of possessions. In today’s world of consumerism and competition, this idea holds timeless relevance, urging us to rediscover balance, gratitude, and the inner richness that material comfort alone can never provide. 

Contentment is a state of inner satisfaction where one feels grateful and complete regardless of circumstances. It is not about giving up ambition but about finding peace in what one already has. Luxury, on the other hand, represents indulgence in material possessions, comfort, and extravagance. It is artificial because it depends on external validation – wealth, power, or status – and breeds an illusion of happiness. When this illusion fades, dissatisfaction reappears, pushing the individual to acquire more. Thus, while contentment enriches the soul, luxury often impoverishes it by making one dependent on endless desires. 

This truth has been celebrated by great thinkers across civilizations. In Indian philosophy, the idea of Santosha (contentment) is considered one of the key virtues for a fulfilling life. The Bhagavad Gita teaches that peace is attained not through possession but through detachment – when one performs one’s duty without obsession with results. The Gita states, “He who is content with whatever comes his way, who has transcended the pairs of opposites, who is free from envy, and who remains balanced in success and failure, is not bound.” Similarly, Buddhism identifies craving (tanha) as the root cause of suffering. The moment one renounces excessive desire, one attains nirvana, the highest state of contentment. Jainism, too, upholds aparigraha (non-possession) as a moral principle, warning that attachment to material things binds the soul. These traditions collectively emphasize that true wealth is inner peace – a wealth that grows when desire is mastered. 

Western philosophy echoes similar ideas. Socrates declared, “He who is not contented with what he has would not be contented with what he would like to have.” The Stoic philosophers of ancient Greece and Rome – such as Seneca, Marcus Aurelius, and Epictetus – taught that virtue and happiness lie in self-control and acceptance. For them, freedom meant liberation from unnecessary desires. Seneca wrote that wealth consists not in great possessions but in few wants. Even in Christian teachings, Jesus Christ spoke of detachment from riches, saying, “Do not store up treasures on earth, where moth and rust destroy.” These ideas converge across traditions, affirming that contentment is a natural wealth accessible to all, while the pursuit of luxury creates artificial poverty that no riches can cure. 

From a psychological perspective, contentment nurtures emotional balance and well-being. It is the mental state where one’s happiness is not conditional on external circumstances. A contented person experiences gratitude, resilience, and satisfaction, leading to mental stability and inner peace. In contrast, luxury often fosters comparison, competition, and restlessness. The modern concept of the “hedonic treadmill” explains this perfectly – when people achieve material success or acquire new luxuries, they experience only a temporary boost in happiness. Soon, they adapt to the new level and crave even more. This endless cycle of wanting more erodes peace of mind, leaving a sense of inner emptiness. Luxury, therefore, creates a paradox – the more one has, the less one feels satisfied. 

In contemporary society, this philosophy holds profound relevance. The 21st century is characterized by consumerism, where luxury is portrayed as the ultimate symbol of success. Advertising and social media glorify extravagant lifestyles, convincing people that happiness lies in what they can buy or display. The result is a generation constantly comparing and competing, often at the cost of mental health. Studies show that despite increasing incomes and access to luxuries, rates of depression and anxiety have also risen worldwide. People may live in comfort yet feel a sense of dissatisfaction – a kind of spiritual poverty amidst material wealth. The quote thus captures the irony of modern civilization: we have mastered the art of living luxuriously but forgotten how to live peacefully. 

Economically and environmentally, the unrestrained pursuit of luxury has created new forms of poverty and inequality. The global economy’s dependence on consumerism has led to unsustainable exploitation of natural resources. Forests are cleared, oceans polluted, and the climate destabilized to meet the demands of luxurious consumption. The irony is that in trying to live better, humanity is making the planet poorer. On the other hand, contentment promotes sustainability. When people learn to live simply, they reduce waste and nurture ecological balance. This idea resonates with Mahatma Gandhi’s belief that “the Earth provides enough to satisfy every man’s need, but not every man’s greed.” Gandhi’s own life exemplified the power of simplicity. Despite leading one of the greatest freedom movements in history, he lived with minimal possessions and practiced contentment as a spiritual discipline. His wealth lay not in comfort but in character. 

The social dimension of the statement is equally significant. Luxury tends to divide societies. When wealth and possessions become measures of worth, inequality deepens, and envy corrodes human relationships. People begin to value each other based on appearance, brand, or lifestyle rather than integrity or compassion. This weakens social cohesion and breeds alienation. In contrast, a culture rooted in contentment values relationships, cooperation, and empathy. It encourages community living and equality. The concept of Sarvodaya – welfare of all – advocated by Gandhi, is based on this very spirit of contentment and sharing. A contented society is peaceful, while a luxury-driven society is restless and competitive. 

The administrative and political dimensions of this philosophy are equally vital. For public servants, contentment is an ethical anchor. A contented civil servant finds satisfaction in public service itself, not in personal gain. Such individuals are less vulnerable to corruption because their happiness does not depend on money or material rewards. They act out of duty and integrity. Conversely, when luxury becomes a goal, morality declines. Corruption, nepotism, and exploitation arise from discontent and greed. Thus, contentment strengthens governance, while luxury undermines it. From a policymaking perspective, governments must recognize that true development is not just about economic growth but about human well-being. Bhutan’s concept of Gross National Happiness (GNH) is a shining example – it measures progress not by GDP but by the contentment and harmony of its citizens. This model reminds us that the ultimate purpose of development is to enrich lives, not just wallets. 

History provides many illustrations of how contentment leads to greatness while the pursuit of luxury leads to downfall. The Buddha, born a prince surrounded by luxury, renounced it all to seek enlightenment and became a symbol of eternal wisdom. Similarly, great leaders and thinkers like Swami Vivekananda, Mother Teresa, and Nelson Mandela lived simple lives yet influenced millions. Their contentment came from purpose, not possessions. In contrast, history also records the decline of empires like Rome and the later Mughal dynasty, where luxury and decadence led to moral and political decay. The same pattern is visible today in modern societies overwhelmed by consumerism and moral fatigue. The lesson remains timeless: civilizations that value contentment endure; those obsessed with luxury collapse under their own excess. 

The concept also has ethical and spiritual implications. Ethics is the science of right living, and contentment is one of its highest virtues. A contented person is free from envy, greed, and deceit. He does not harm others for personal gain because he feels no lack within. Spiritual traditions around the world regard contentment as the gateway to enlightenment. It brings humility, gratitude, and compassion – the virtues that elevate human consciousness. Luxury, on the contrary, can lead to arrogance, vanity, and moral blindness. When comfort becomes an addiction, conscience weakens. Thus, spiritual poverty often hides behind material riches. True spirituality is not about renouncing life but about enjoying it with detachment and simplicity. 

In today’s fast-paced digital age, where success is often equated with wealth and visibility, the need to rediscover contentment is more urgent than ever. Technology and social media have created an illusion of constant progress, but also a culture of comparison. People chase likes, followers, and virtual admiration – new forms of luxury that mimic happiness but breed anxiety. The more one chases external validation, the more one loses connection with inner peace. The minimalist and mindfulness movements emerging globally reflect humanity’s silent yearning to return to simplicity. People are beginning to realize that decluttering their homes, schedules, and minds brings more joy than accumulating possessions. The COVID-19 pandemic further reinforced this realization. When the world came to a standstill, people learned that real wealth is not luxury cars or designer clothes but health, relationships, and peace of mind. 

However, it is important to clarify that contentment should not be mistaken for complacency. A contented person may still have ambitions and dreams, but he pursues them with balance and integrity. Contentment and aspiration are not enemies; they are complementary. Contentment provides inner stability, while aspiration gives direction. Without contentment, ambition becomes greed; without ambition, contentment becomes stagnation. Similarly, luxury itself is not evil. Art, beauty, and comfort have their rightful place in human civilization. The danger arises when luxury becomes an end in itself and begins to define human worth. The key is moderation – to enjoy luxury without being enslaved by it, to seek progress without losing peace. 

“Contentment is natural wealth; luxury is artificial poverty” offers a timeless message for individuals and societies alike. It reminds us that true wealth lies not in the abundance of possessions but in the abundance of peace. Contentment is the natural state of the soul – pure, self-sufficient, and fulfilling – while luxury, when pursued without purpose, is an illusion that drains both moral and spiritual energy. A person who is content, even with little, is richer than one who owns the world yet feels empty within. The principle extends beyond personal life to governance, economics, and sustainability, making it a universal truth for all times. As the saint Kabir beautifully said, “Santoshi sahib bhavani, lobhi nar narak samani” – the contented live like gods, the greedy dwell in misery. The world today, more than ever, needs to remember this wisdom: that happiness does not come from having everything, but from being thankful for what we already have. Luxury fades with time, but contentment endures forever – the only wealth that truly belongs to us."""
initial_state: EssayState = {
    "topic": topic,
    "essay": essay
}

result = workflow.invoke(initial_state)
pretty_print(result)